// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRCEqfqD-pPa_NpKBAQxH2dg4QbWZ6ww',
    appId: '1:595473560230:web:72f61258971481ae50ba67',
    messagingSenderId: '595473560230',
    projectId: 'yojana-mitra-a3f2c',
    authDomain: 'yojana-mitra-a3f2c.firebaseapp.com',
    storageBucket: 'yojana-mitra-a3f2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuB53xgba1o9euFIY2ADfHdjEI2UhAVs8',
    appId: '1:595473560230:android:e4c1eab34dc5649a50ba67',
    messagingSenderId: '595473560230',
    projectId: 'yojana-mitra-a3f2c',
    storageBucket: 'yojana-mitra-a3f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5e6xdptwqlgVcIvem6MNnazZovxGcdpk',
    appId: '1:595473560230:ios:0cb8cac6e9b4f32950ba67',
    messagingSenderId: '595473560230',
    projectId: 'yojana-mitra-a3f2c',
    storageBucket: 'yojana-mitra-a3f2c.firebasestorage.app',
    iosBundleId: 'com.example.yojanaMitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5e6xdptwqlgVcIvem6MNnazZovxGcdpk',
    appId: '1:595473560230:ios:0cb8cac6e9b4f32950ba67',
    messagingSenderId: '595473560230',
    projectId: 'yojana-mitra-a3f2c',
    storageBucket: 'yojana-mitra-a3f2c.firebasestorage.app',
    iosBundleId: 'com.example.yojanaMitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTRCEqfqD-pPa_NpKBAQxH2dg4QbWZ6ww',
    appId: '1:595473560230:web:98dbc58ca746a92950ba67',
    messagingSenderId: '595473560230',
    projectId: 'yojana-mitra-a3f2c',
    authDomain: 'yojana-mitra-a3f2c.firebaseapp.com',
    storageBucket: 'yojana-mitra-a3f2c.firebasestorage.app',
  );
}
